Repository alliedmodders/amxmodx, pull requests merged in 2018-07, with the labels that each got.

#490 Fix for precache_event
  amxmodx/amxmodx.cpp
Labels: bug, core

#478 Improved mprop description
  plugins/include/newmenus.inc
Labels: core, documentation

#477 Macedonian & Bulgarian translation fix
  plugins/lang/admin.txt
  plugins/lang/adminchat.txt
  plugins/lang/admincmd.txt
  plugins/lang/adminhelp.txt
  plugins/lang/adminslots.txt
  plugins/lang/adminvote.txt
  plugins/lang/antiflood.txt
  plugins/lang/cmdmenu.txt
  plugins/lang/common.txt
  plugins/lang/imessage.txt
  plugins/lang/mapchooser.txt
  plugins/lang/menufront.txt
  plugins/lang/miscstats.txt
  plugins/lang/multilingual.txt
  plugins/lang/nextmap.txt
  plugins/lang/pausecfg.txt
  plugins/lang/plmenu.txt
  plugins/lang/restmenu.txt
  plugins/lang/scrollmsg.txt
  plugins/lang/stats_dod.txt
  plugins/lang/statscfg.txt
  plugins/lang/statsx.txt
  plugins/lang/telemenu.txt
  plugins/lang/time.txt
  plugins/lang/timeleft.txt
Labels: translation

#471 Fix a menu recursion issue
  amxmodx/CGameConfigs.h
  amxmodx/amxmodx.cpp
  amxmodx/newmenus.cpp
Labels: bug, core, regression

#474 Hungarian language update
  plugins/lang/admin.txt
  plugins/lang/adminchat.txt
  plugins/lang/admincmd.txt
  plugins/lang/adminhelp.txt
  plugins/lang/adminslots.txt
  plugins/lang/adminvote.txt
  plugins/lang/antiflood.txt
  plugins/lang/cmdmenu.txt
  plugins/lang/common.txt
  plugins/lang/imessage.txt
  plugins/lang/mapchooser.txt
  plugins/lang/mapsmenu.txt
  plugins/lang/menufront.txt
  plugins/lang/miscstats.txt
  plugins/lang/multilingual.txt
  plugins/lang/nextmap.txt
  plugins/lang/pausecfg.txt
  plugins/lang/plmenu.txt
  plugins/lang/restmenu.txt
  plugins/lang/scrollmsg.txt
  plugins/lang/statscfg.txt
  plugins/lang/statsx.txt
  plugins/lang/telemenu.txt
  plugins/lang/time.txt
  plugins/lang/timeleft.txt
Labels: translation

#489 API documentation fix for some .inc files
  plugins/include/amxmodx.inc
  plugins/include/core.inc
  plugins/include/file.inc
  plugins/include/float.inc
  plugins/include/fun.inc
  plugins/include/lang.inc
  plugins/include/time.inc
Labels: documentation

#491 Lack register_event() on event_enable/disable
  plugins/include/amxmodx.inc
Labels: documentation, enhancement

#494 Further Hungarian translation update
  plugins/lang/adminchat.txt
  plugins/lang/admincmd.txt
  plugins/lang/adminvote.txt
  plugins/lang/common.txt
  plugins/lang/mapchooser.txt
  plugins/lang/miscstats.txt
  plugins/lang/multilingual.txt
  plugins/lang/pausecfg.txt
  plugins/lang/scrollmsg.txt
  plugins/lang/statscfg.txt
  plugins/lang/statsx.txt
Labels: enhancement, translation

#496 Fix typos in few localinfo identifiers for the AMXX config directory retrieval (bug 6629)
  amxmodx/CoreConfig.cpp
Labels: bug, core

#495 Fix a buffer issue in RegisterHam
  modules/hamsandwich/hook.h
  modules/hamsandwich/hook_native.cpp
Labels: bug, module: hamsandwich

#473 Add MPROP_SHOWPAGE
  amxmodx/newmenus.cpp
  amxmodx/newmenus.h
  plugins/include/newmenus.inc
Labels: core, enhancement

#503 Fix a buffer issue in server_changelevel forward caused by engine_changelevel native
  amxmodx/amxmodx.cpp
Labels: bug, core

#499 Fix a compilation regression in LookupLangKey (introduced with #222)
  plugins/include/lang.inc
Labels: regression

#504 Fix client_print_color where the color is ignored if string starts with an unicode character
  amxmodx/amxmodx.cpp
Labels: bug, core

#508 Fix a buffer issue in EngFunc_LightStyle
  modules/fakemeta/engfunc.cpp
Labels: bug, module: fakemeta
