Repository alliedmodders/amxmodx, pull requests merged in 2019-04, with the labels that each got.

#674 Updated Portuguese Brazilian translation in miscstats.txt
  plugins/lang/miscstats.txt
Labels: enhancement, translation

#685 Remove additional parameter
  plugins/include/message_const.inc
Labels: documentation

#687 Add new public var with mapname and new constant
  amxmodx/CPlugin.cpp
  amxmodx/amxmodx.cpp
  plugins/include/amxconst.inc
  public/engine_strucs.h
Labels: core, enhancement

#704 String formatted incorrectly at checkKills() fix
  plugins/cstrike/miscstats.sma
Labels: bug, plugin
