Repository alliedmodders/amxmodx, pull requests merged in 2019-01, with the labels that each got.

#663 Fix typo in json_parse documentation
  plugins/include/json.inc
Labels: documentation, typo

#662 Revert RETURN_META(MRES_HANDLED);
  modules/fun/fun.cpp
Labels: module: fun, typo

#661 Update Hungarian translation in miscstats.txt with latest additions
  plugins/lang/miscstats.txt
Labels: enhancement, translation

#671 Add player validation for menu_display
  amxmodx/newmenus.cpp
Labels: core, enhancement

#667 Menu buttons stayed english in Plugin's cvar/command menus
  plugins/pluginmenu.sma
Labels: enhancement, plugin
