Repository alliedmodders/amxmodx, pull requests merged in 2019-06, with the labels that each got.

#730 Fix typo on engine.inc documentation
  plugins/include/engine.inc
Labels: documentation, typo

#726 Fix MPROP_SHOWPAGE option not working as expected
  amxmodx/newmenus.cpp
Labels: bug, core, typo

#698 Albanian Language translation support
  plugins/lang/admin.txt
  plugins/lang/adminchat.txt
  plugins/lang/admincmd.txt
  plugins/lang/adminhelp.txt
  plugins/lang/adminslots.txt
  plugins/lang/adminvote.txt
  plugins/lang/antiflood.txt
  plugins/lang/cmdmenu.txt
  plugins/lang/common.txt
  plugins/lang/imessage.txt
  plugins/lang/languages.txt
  plugins/lang/mapchooser.txt
  plugins/lang/mapsmenu.txt
  plugins/lang/menufront.txt
  plugins/lang/miscstats.txt
  plugins/lang/multilingual.txt
  plugins/lang/nextmap.txt
  plugins/lang/pausecfg.txt
  plugins/lang/plmenu.txt
  plugins/lang/restmenu.txt
  plugins/lang/scrollmsg.txt
  plugins/lang/stats_dod.txt
  plugins/lang/statscfg.txt
  plugins/lang/statsx.txt
  plugins/lang/telemenu.txt
  plugins/lang/time.txt
  plugins/lang/timeleft.txt
Labels: translation

#664 Add square distance functions to xs.inc
  plugins/include/xs.inc
Labels: enhancement, plugin
