Repository alliedmodders/amxmodx, pull requests merged in 2019-10, with the labels that each got.

#764 Fix GeoIP2 database file extraction
  support/buildbot/package.pl
Labels: ambuild, bug

#763 Send pre-formatted string in SayText and TextMSg as a parameter instead of as the format string
  amxmodx/util.cpp
Labels: core

#759 (1.9-dev) Compiler: Fix undefined symbol: pow10
  compiler/libpc300/sc2.c
Labels: compiler

#750 European Portuguese Language translation support
  plugins/lang/admin.txt
  plugins/lang/adminchat.txt
  plugins/lang/admincmd.txt
  plugins/lang/adminhelp.txt
  plugins/lang/adminslots.txt
  plugins/lang/adminvote.txt
  plugins/lang/antiflood.txt
  plugins/lang/cmdmenu.txt
  plugins/lang/common.txt
  plugins/lang/imessage.txt
  plugins/lang/languages.txt
  plugins/lang/mapchooser.txt
  plugins/lang/mapsmenu.txt
  plugins/lang/menufront.txt
  plugins/lang/miscstats.txt
  plugins/lang/multilingual.txt
  plugins/lang/nextmap.txt
  plugins/lang/pausecfg.txt
  plugins/lang/plmenu.txt
  plugins/lang/restmenu.txt
  plugins/lang/scrollmsg.txt
  plugins/lang/stats_dod.txt
  plugins/lang/statscfg.txt
  plugins/lang/statsx.txt
  plugins/lang/telemenu.txt
  plugins/lang/time.txt
  plugins/lang/timeleft.txt
Labels: translation

#723 Add new plugin defines regarding the AMX Mod X version
  support/generate_headers.py
Labels: enhancement, plugin

#770 Fix geoip_latitude/longitude natives returning incorrect values under linux/osx
  modules/geoip/AMBuilder
  modules/geoip/msvc12/geoip.vcxproj
  third_party/libmaxminddb/maxminddb_config.h
Labels: bug, module: geoip

#761 Fixes to read_args and read_argv* natives
  amxmodx/amxmodx.cpp
Labels: bug, core

#778 Fix new lines with TextMsg and SayText (side-effect of #763)
  amxmodx/amxmodx.cpp
  amxmodx/amxmodx.h
  amxmodx/meta_api.cpp
  amxmodx/util.cpp
Labels: core
