Repository alliedmodders/amxmodx, pull requests merged in 2020-05, with the labels that each got.

#862 Turkish Translation Fixes/Addings
  plugins/lang/admin.txt
  plugins/lang/adminchat.txt
  plugins/lang/admincmd.txt
  plugins/lang/adminhelp.txt
  plugins/lang/adminslots.txt
  plugins/lang/adminvote.txt
  plugins/lang/antiflood.txt
  plugins/lang/cmdmenu.txt
  plugins/lang/common.txt
  plugins/lang/imessage.txt
  plugins/lang/mapchooser.txt
  plugins/lang/mapsmenu.txt
  plugins/lang/menufront.txt
  plugins/lang/miscstats.txt
  plugins/lang/multilingual.txt
  plugins/lang/nextmap.txt
  plugins/lang/pausecfg.txt
  plugins/lang/plmenu.txt
  plugins/lang/restmenu.txt
  plugins/lang/scrollmsg.txt
  plugins/lang/stats_dod.txt
  plugins/lang/statscfg.txt
  plugins/lang/statsx.txt
  plugins/lang/telemenu.txt
  plugins/lang/time.txt
  plugins/lang/timeleft.txt
Labels: translation

#851 Fix broken DoD Fun module natives
  modules/dod/dodfun/CMisc.h
  modules/dod/dodfun/NPD.cpp
Labels: bug, module: dodfun

#823 adminvote.sma exploit fix
  plugins/adminvote.sma
Labels: enhancement, plugin

#822 admincmd.sma exploits fix
  plugins/admincmd.sma
Labels: enhancement, plugin

#816 Yet another Hungarian language revise
  plugins/lang/admincmd.txt
  plugins/lang/adminhelp.txt
  plugins/lang/mapchooser.txt
  plugins/lang/menufront.txt
  plugins/lang/pausecfg.txt
  plugins/lang/statsx.txt
Labels: enhancement, translation

#714 Public vars for plugin data
  amxmodx/CPlugin.cpp
  amxmodx/CPlugin.h
  amxmodx/amxmodx.cpp
  amxmodx/srvcmd.cpp
  plugins/include/amxmodx.inc
Labels: core, enhancement

#826 Add menu_item_setaccess native
  amxmodx/newmenus.cpp
  plugins/include/newmenus.inc
Labels: core
