Repository alliedmodders/amxmodx, pull requests merged in 2021-09, with the labels that each got.

#990 FIX typo in message_const.inc TE_FIZZ comment
  plugins/include/message_const.inc
Labels: enhancement, documentation

#992 [FEATURE REQUEST] set_hudmessage add missing parameters
  amxmodx/amxmodx.cpp
  amxmodx/util.cpp
  plugins/include/amxmodx.inc
Labels: enhancement, core

#926 Minor German Language Update
  plugins/lang/admincmd.txt
  plugins/lang/adminvote.txt
  plugins/lang/mapsmenu.txt
  plugins/lang/menufront.txt
  plugins/lang/miscstats.txt
  plugins/lang/nextmap.txt
  plugins/lang/restmenu.txt
  plugins/lang/stats_dod.txt
  plugins/lang/statscfg.txt
  plugins/lang/statsx.txt
Labels: enhancement, translation

#902 European Portuguese Language translation fixes
  plugins/lang/admin.txt
  plugins/lang/admincmd.txt
  plugins/lang/adminslots.txt
  plugins/lang/common.txt
  plugins/lang/menufront.txt
  plugins/lang/miscstats.txt
  plugins/lang/pausecfg.txt
  plugins/lang/restmenu.txt
  plugins/lang/statscfg.txt
Labels: enhancement, translation
